#
# First example of a tacoscript following the syntax of Salt
# but not implementing all options
# https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html
#
# unique id of the task, can be any string
pack-result:
  cmd.run:
    - names:
        - tar czf /tmp/my-date.tar.gz /tmp/my-date.txt
        - mv /tmp/my-date.tar.gz /tmp/mydate
    - require:
        - save-date
        - remove-date
        - create-folder
    - creates:
        - /tmp/my-date.tar.gz
save-date:
  # Name of the class and the module
  cmd.run:
    - name: /bin/date > /tmp/my-date.txt
    - cwd: /tmp
    - user: www-data
    - shell: bash
    - env:
        - PASSWORD: bunny
    - creates: /tmp/my-date.txt # Don't execute if file exists.
remove-date:
  cmd.run:
    - name: rm /tmp/my-date.txt
    - shell: bash
    - require:
        - save-date
    - onlyif: date +%c|grep -q "^Fri" # Execute only on Thursdays
create-folder:
  cmd.run:
    - names:
        - mkdir /tmp/mydate
    - unless: test -e /tmp/mydate
