#
# First example of a tacoscript following the syntax of Salt
# but not implementing all options
# https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html
#
# unique id of the task, can be any string
testing1:
  cmd.run:
    - names:
      - echo ${PASSWORD}
      - ls -la
    - cwd: /Users/breathbath/Projects
    - shell: zsh
    - env:
        - PASSWORD: bunny
    - require:
        - testing2
testing2:
  cmd.run:
    - names:
        - echo "I am first"
    - pwd: /Users/breathbath/Projects
