#
# First example of a tacoscript following the syntax of Salt
# but not implementing all options
# https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html
#
# unique id of the task, can be any string
cwd:
  # Name of the class and the module
  cmd.run:
    - names:
      - echo ${PASSWORD}
      - ls -la
    - cwd: /Users/breathbath/Projects
    - shell: zsh
    - env:
        - PASSWORD: bunny
    # - creates: /tmp/my-date.txt
    #- user: root
